In [ ]:
import pandas as pd

df = pd.read_csv("../data/household_power_consumption.txt", sep=';', low_memory=False)

In [2]:
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])

C:\Users\yasmi\AppData\Local\Temp\ipykernel_13744\2991691273.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])

In [3]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3', 'Datetime'],
      dtype='object')

In [ ]:
df = pd.read_csv("../data/household_power_consumption_clean.csv")

C:\Users\yasmi\AppData\Local\Temp\ipykernel_13744\4036957523.py:1: DtypeWarning: Columns (2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("household_power_consumption_clean.csv")

In [5]:
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])

C:\Users\yasmi\AppData\Local\Temp\ipykernel_13744\2991691273.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])

In [6]:
df[['Date','Time','Datetime']].head()

         Date      Time            Datetime
0  16/12/2006  17:24:00 2006-12-16 17:24:00
1  16/12/2006  17:25:00 2006-12-16 17:25:00
2  16/12/2006  17:26:00 2006-12-16 17:26:00
3  16/12/2006  17:27:00 2006-12-16 17:27:00
4  16/12/2006  17:28:00 2006-12-16 17:28:00

In [7]:
df.set_index('Datetime', inplace=True)

In [8]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,,,
2006-12-16 17:24:00,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
2006-12-16 17:25:00,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2006-12-16 17:26:00,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
2006-12-16 17:27:00,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
2006-12-16 17:28:00,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

In [9]:
df.drop(columns=['Date','Time'], inplace=True)

In [10]:
df.apply(pd.to_numeric, errors='coerce').head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,
2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [11]:
df.dtypes

Global_active_power       object
Global_reactive_power     object
Voltage                   object
Global_intensity          object
Sub_metering_1            object
Sub_metering_2            object
Sub_metering_3           float64
dtype: object

In [12]:
cols = ['Global_active_power','Global_reactive_power','Voltage',
        'Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3']

df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [13]:
df.isna().sum()

Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [14]:
df=df.dropna()

In [15]:
df=df.sort_index()

In [16]:
df.tail()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,
2010-11-26 20:58:00,0.946,0.0,240.43,4.0,0.0,0.0,0.0
2010-11-26 20:59:00,0.944,0.0,240.00,4.0,0.0,0.0,0.0
2010-11-26 21:00:00,0.938,0.0,239.82,3.8,0.0,0.0,0.0
2010-11-26 21:01:00,0.934,0.0,239.70,3.8,0.0,0.0,0.0
2010-11-26 21:02:00,0.932,0.0,239.55,3.8,0.0,0.0,0.0

In [17]:
df.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,
2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [18]:
power_hourly = df['Global_active_power'].resample('H').mean()

C:\Users\yasmi\AppData\Local\Temp\ipykernel_13744\1918182424.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  power_hourly = df['Global_active_power'].resample('H').mean()

In [19]:
power_hourly = power_hourly.dropna()

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
power_scaled = scaler.fit_transform(power_hourly.values.reshape(-1,1))

In [21]:
import pandas as pd
power_scaled = pd.DataFrame(power_scaled, index=power_hourly.index, columns=['scaled_power'])

In [22]:
split_index = int(len(power_scaled) * 0.8)

In [23]:
train = power_scaled.iloc[:split_index]
test = power_scaled.iloc[split_index:]

In [24]:
print("Train shape:", train.shape)
print("Test shape:", test.shape)

Train shape: (27334, 1)
Test shape: (6834, 1)

In [ ]:
power_scaled.to_csv("../data/final_prepared_data.csv")