In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("household_power_consumption.xls", sep=';')

In [5]:
df.head()

  Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0  16/12/2006,17:24:00,4.216,0.418,234.840,18.400...
1  16/12/2006,17:25:00,5.360,0.436,233.630,23.000...
2  16/12/2006,17:26:00,5.374,0.498,233.290,23.000...
3  16/12/2006,17:27:00,5.388,0.502,233.740,23.000...
4  16/12/2006,17:28:00,3.666,0.528,235.680,15.800...

In [6]:
df.to_csv("household_power_consumption.csv", index=False)

In [7]:
df = pd.read_csv("household_power_consumption.csv")

In [8]:
df.head()

  Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0  16/12/2006,17:24:00,4.216,0.418,234.840,18.400...
1  16/12/2006,17:25:00,5.360,0.436,233.630,23.000...
2  16/12/2006,17:26:00,5.374,0.498,233.290,23.000...
3  16/12/2006,17:27:00,5.388,0.502,233.740,23.000...
4  16/12/2006,17:28:00,3.666,0.528,235.680,15.800...

In [9]:
df.shape

(2075259, 1)

In [11]:
df.columns

Index(['Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3'], dtype='object')

In [12]:
df.tail()

        Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
2075254  26/11/2010,20:58:00,0.946,0.0,240.43,4.0,0.0,0...
2075255  26/11/2010,20:59:00,0.944,0.0,240.0,4.0,0.0,0....
2075256  26/11/2010,21:00:00,0.938,0.0,239.82,3.8,0.0,0...
2075257  26/11/2010,21:01:00,0.934,0.0,239.7,3.8,0.0,0....
2075258  26/11/2010,21:02:00,0.932,0.0,239.55,3.8,0.0,0...

In [13]:
df.dtypes

Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3    object
dtype: object

In [14]:
df.isna().sum()

Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3    0
dtype: int64

In [15]:
df.describe()

       Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count                                             2075259
unique                                            2075259
top     16/12/2006,17:24:00,4.216,0.418,234.840,18.400...
freq                                                    1